[package]
name = "weeb_3"
version = "0.0.0"
edition = "2021"
license = "MIT"

[package.metadata.release]
release = false

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = { git = "https://github.com/tokio-rs/bytes.git" }
prost = { git = "https://github.com/tokio-rs/prost.git" }
prost-types = { git = "https://github.com/tokio-rs/prost.git" }
anyhow = { git = "https://github.com/dtolnay/anyhow.git" }
rand = "0.8"
tracing = { git = "https://github.com/tokio-rs/tracing.git" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing.git" , features = ["env-filter"] }

[build-dependencies]
prost-build = { git = "https://github.com/tokio-rs/prost.git" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { git = "https://github.com/tokio-rs/axum.git" }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", features = [ "ecdsa", "ed25519", "macros", "ping", "tokio"] }
libp2p-webrtc = { git = "https://github.com/libp2p/rust-libp2p.git",  features = [ "tokio"] }
libp2p-tcp = { git = "https://github.com/libp2p/rust-libp2p.git",  features = ["tokio"] }
rust-embed = { git = "https://github.com/pyrossh/rust-embed.git", features = ["include-exclude", "interpolate-folder-path"] }
tokio = { default-features = false, features = ["macros", "net", "rt", "signal", "rt-multi-thread"] }
tokio-util = { features = ["compat"] }
tower = { git = "https://github.com/tower-rs/tower.git" }
tower-http = { git = "https://github.com/tower-rs/tower-http.git", features = ["cors"] }
mime_guess = { git = "https://github.com/abonander/mime_guess.git" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.69"
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", features = [ "ecdsa", "ed25519", "macros", "ping", "tokio", "wasm-bindgen"] }
libp2p-webrtc-websys = { git = "https://github.com/libp2p/rust-libp2p.git" }
tracing-wasm = { git = "https://github.com/old-storyai/tracing-wasm.git" }
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3", features = ['Document', 'Element', 'HtmlElement', 'Node', 'Response', 'Window'] }
