[package]
name = "weeb_3"
version = "0.0.0"
edition = "2021"
authors = ["Weeb_3"]
description = "Ara ara"
license = "MIT"
repository = "https://github.com/weeb_3/weeb_3"

[package.metadata.release]
release = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.81"
futures = "0.3.30"
rand = "0.8"
tracing = { git = "https://github.com/tokio-rs/tracing.git" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = "0.7.5"
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", features = [ "ed25519", "macros", "ping", "tokio"] }
libp2p-webrtc = { git = "https://github.com/libp2p/rust-libp2p.git",  features = ["tokio"] }
libp2p-tcp = { git = "https://github.com/libp2p/rust-libp2p.git",  features = ["tokio"] }
rust-embed = { version = "8.3.0", features = ["include-exclude", "interpolate-folder-path"] }
tokio = { version = "1.37", default-features = false, features = ["macros", "net", "rt", "signal", "rt-multi-thread"] }
tokio-util = { version = "0.7", features = ["compat"] }
tower = "0.4"
tower-http = { version = "0.5.2", features = ["cors"] }
mime_guess = "2.0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.69"
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", features = [ "ed25519", "macros", "ping", "tokio", "wasm-bindgen"] }
libp2p-webrtc-websys = { git = "https://github.com/libp2p/rust-libp2p.git" }
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3", features = ['Document', 'Element', 'HtmlElement', 'Node', 'Response', 'Window'] }
